### ISSUE TITLE
How to translate

### ISSUE THREAD

**Issue by VDK** [magnusmanske/cradle#7]
Where can a translation be contributed?

Also: newcomers seemed to be confused by the word "alias". In the Wikidata interface this field is labeled as "Also known as". Might be better to do that in Cradle as well.

**Comment by magnusmanske** [comment]
The translation can be seen and amended via the "globe" button in the header bar:
https://tooltranslate.toolforge.org/#tool=37&languages=en

**Comment by magnusmanske** [comment]
You can change "alias" there is you like.
